### ISSUE TITLE
nest-cli state command broken (as of 3pm MST, 7-29-2016)

### ISSUE THREAD

**Issue by Shafik23** [jasonmit/nest-cli#4]
Ths was working fine for the last month. I have it on a cron-job to turn my thermostat on and off. 

Today it broke with the following error:
shafik@Khaleesi:~/logs$ nest-cli state cool
error:  Error: Bad Request
    at checkStatus (/usr/local/lib/node_modules/nest-cli/lib/api/utils/fetch.js:13:19)
    at run (/usr/local/lib/node_modules/nest-cli/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/nest-cli/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/nest-cli/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

nest-cli read/ls are fine:

shafik@Khaleesi:~/logs$ nest-cli read
┌─────────────────────────┬──────────────────────────────────┐
│ ID                      │ -removed-           │
├─────────────────────────┼──────────────────────────────────┤
│ Name                    │ Upstairs                         │
├─────────────────────────┼──────────────────────────────────┤
│ State                   │ cooling                          │
├─────────────────────────┼──────────────────────────────────┤
│ Mode                    │ cool                             │
├─────────────────────────┼──────────────────────────────────┤
│ Humidity                │ 35                               │
├─────────────────────────┼──────────────────────────────────┤
│ Target Temperature      │ 84°F                             │
├─────────────────────────┼──────────────────────────────────┤
│ Target Temperature Low  │ 71°F                             │
├─────────────────────────┼──────────────────────────────────┤
│ Target Temperature High │ 73°F                             │

**Comment by jasonmit** [comment]
I tried with a fresh account and couldn't reproduce this.  Maybe try recreating these steps https://github.com/jasonmit/nest-cli#configuring-the-application

**Comment by Shafik23** [comment]
Thanks for looking into this Jason. I just tried it and **I cannot reproduce the problem anymore**, so perhaps it was some intermittent issue with the Nest servers (it was down for about 5 hours).

**Comment by Shafik23** [comment]
Problem doesn't seem related to nest-cli itself.
